import "@/styles/globals.css";

import { type Metadata } from "next";
import { antic, chivo } from "@/styles/fonts";
import UnwrappedNavbar from "@/components/Navbar";
import type { NavbarProps } from "@/types";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const navbarProps: NavbarProps = {
  title: {
    label: "REVERB",
    href: "/",
  },
  styling: {
    title: {
      text: "text-green-500",
      hover: "hover:text-white",
      font: antic.className,
    },
    bg: "bg-inherit",
    item: {
      text: "text-zinc-300",
      hover: "hover:text-white",
    },
    icon: {
      text: "text-zinc-300",
      hover: "hover:text-white",
    },
  },
  navItems: [
    {
      label: "Features",
      href: "#features",
    },
    {
      label: "About",
      href: "#about",
    },
    {
      label: "Dashboard",
      href: "/dashboard",
    },
  ],
  includeSocials: {
    github: "https://github.com/udbhavbalaji",
    linkedin: "https://linkedin.com/in/udbhav-balaji",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        layout: {
          socialButtonsPlacement: "bottom",
        },
        variables: {
          colorPrimary: "#22c55e",
          colorText: "white",
          colorTextOnPrimaryBackground: "black",
          colorTextSecondary: "#94a3b8",
          colorBackground: "#09090b",
          fontFamily: "chivo",
          //note: need to change the fonts a bit
          // fontFamilyButtons: "antic",
          borderRadius: "0.5rem",
        },
      }}
    >
      <html lang="en" className={`${chivo.variable}`}>
        <body>
          <div
            className={`${chivo.className} min-h-screen bg-gradient-to-b from-[#191414] via-black to-[#121212] text-white`}
          >
            <UnwrappedNavbar />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
